language:
  - python
  - cpp
compiler:
  - clang
  - gcc
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - ./configure && make
install:
  - "python setup.py install"
script:
  - "python setup.py test"
